package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/kylejs/splitty/backend/graph/model"
)

// SignInWithApple is the resolver for the signInWithApple field.
func (r *mutationResolver) SignInWithApple(ctx context.Context, identityToken string) (*model.AuthResponse, error) {
	panic(fmt.Errorf("not implemented: SignInWithApple - signInWithApple"))
}

// SendPasscode is the resolver for the sendPasscode field.
func (r *mutationResolver) SendPasscode(ctx context.Context, email string) (*model.SendPasscodeResponse, error) {
	panic(fmt.Errorf("not implemented: SendPasscode - sendPasscode"))
}

// VerifyPasscode is the resolver for the verifyPasscode field.
func (r *mutationResolver) VerifyPasscode(ctx context.Context, email string, code string) (*model.AuthResponse, error) {
	panic(fmt.Errorf("not implemented: VerifyPasscode - verifyPasscode"))
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, refreshToken string) (*model.AuthResponse, error) {
	panic(fmt.Errorf("not implemented: RefreshToken - refreshToken"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
