package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"errors"
	"fmt"
	"log"

	pgx "github.com/jackc/pgx/v5"
	"github.com/kylejs/splitty/backend/graph/dataloader"
	"github.com/kylejs/splitty/backend/graph/model"
	"github.com/kylejs/splitty/backend/internal/auth"
	"github.com/kylejs/splitty/backend/internal/group"
)

// Members is the resolver for the members field.
func (r *groupResolver) Members(ctx context.Context, obj *model.Group) ([]*model.User, error) {
	loaders := dataloader.For(ctx)
	ids, err := loaders.GroupMembersLoader.Load(ctx, obj.ID)
	if err != nil {
		return nil, fmt.Errorf("load members: %w", err)
	}
	if len(ids) == 0 {
		return []*model.User{}, nil
	}
	records, err := loaders.UserLoader.LoadAll(ctx, ids)
	if err != nil {
		return nil, fmt.Errorf("load member users: %w", err)
	}
	users := make([]*model.User, len(records))
	for i, u := range records {
		users[i] = userRecordToModel(u)
	}
	return users, nil
}

// Transactions is the resolver for the transactions field.
func (r *groupResolver) Transactions(ctx context.Context, obj *model.Group) ([]*model.Transaction, error) {
	records, err := dataloader.For(ctx).GroupTransactionsLoader.Load(ctx, obj.ID)
	if err != nil {
		return nil, fmt.Errorf("load transactions: %w", err)
	}
	txns := make([]*model.Transaction, len(records))
	for i, t := range records {
		txns[i] = txnRecordToModel(t)
	}
	return txns, nil
}

// CreatedBy is the resolver for the createdBy field.
func (r *groupResolver) CreatedBy(ctx context.Context, obj *model.Group) (*model.User, error) {
	u, err := dataloader.For(ctx).UserLoader.Load(ctx, obj.CreatedByID)
	if err != nil {
		return nil, fmt.Errorf("load group creator: %w", err)
	}
	return userRecordToModel(u), nil
}

// SignInWithApple is the resolver for the signInWithApple field.
func (r *mutationResolver) SignInWithApple(ctx context.Context, identityToken string) (*model.AuthResponse, error) {
	return nil, fmt.Errorf("not implemented: SignInWithApple")
}

// SendPasscode is the resolver for the sendPasscode field.
func (r *mutationResolver) SendPasscode(ctx context.Context, email string) (*model.SendPasscodeResponse, error) {
	if err := r.PasscodeService.SendPasscode(ctx, email); err != nil {
		if errors.Is(err, auth.ErrUnavailable) {
			return nil, fmt.Errorf("email passcode is not available")
		}
		return nil, err
	}
	return &model.SendPasscodeResponse{Success: true}, nil
}

// VerifyPasscode is the resolver for the verifyPasscode field.
func (r *mutationResolver) VerifyPasscode(ctx context.Context, email string, code string) (*model.AuthResponse, error) {
	result, err := r.PasscodeService.VerifyPasscode(ctx, email, code)
	if err != nil {
		if errors.Is(err, auth.ErrUnavailable) {
			return nil, fmt.Errorf("email passcode is not available")
		}
		return nil, err
	}
	return &model.AuthResponse{
		AccessToken:  result.AccessToken,
		RefreshToken: result.RefreshToken,
		User:         userRecordToModel(result.User),
	}, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, refreshToken string) (*model.AuthResponse, error) {
	if r.TokenService == nil {
		return nil, fmt.Errorf("token refresh requires JWT_PRIVATE_KEY to be configured")
	}

	userID, err := r.TokenService.ValidateRefreshToken(ctx, refreshToken)
	if err != nil {
		log.Printf("validate refresh token: %v", err)
		return nil, fmt.Errorf("invalid refresh token")
	}

	user, err := r.UserStore.GetByID(ctx, userID)
	if err != nil {
		log.Printf("lookup user %s: %v", userID, err)
		return nil, fmt.Errorf("failed to refresh token")
	}

	newRefresh, err := r.TokenService.RotateRefreshToken(ctx, refreshToken, userID)
	if err != nil {
		log.Printf("rotate refresh token for user %s: %v", userID, err)
		return nil, fmt.Errorf("failed to refresh token")
	}

	newAccess, err := r.TokenService.GenerateAccessToken(userID, user.Email)
	if err != nil {
		log.Printf("generate access token for user %s: %v", userID, err)
		return nil, fmt.Errorf("failed to refresh token")
	}

	return &model.AuthResponse{
		AccessToken:  newAccess,
		RefreshToken: newRefresh,
		User:         userRecordToModel(user),
	}, nil
}

// CreateGroup is the resolver for the createGroup field.
func (r *mutationResolver) CreateGroup(ctx context.Context, input model.CreateGroupInput) (*model.Group, error) {
	userID, err := r.requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	g, err := r.GroupStore.CreateGroup(ctx, input.Name, userID)
	if err != nil {
		return nil, fmt.Errorf("create group: %w", err)
	}
	return groupRecordToModel(g), nil
}

// AddMemberToGroup is the resolver for the addMemberToGroup field.
func (r *mutationResolver) AddMemberToGroup(ctx context.Context, groupID string, email string) (*model.Group, error) {
	if _, err := r.requireGroupMember(ctx, groupID); err != nil {
		return nil, err
	}

	normalized, err := auth.NormalizeEmail(email)
	if err != nil {
		return nil, fmt.Errorf("invalid email: %w", err)
	}

	user, err := r.UserStore.GetByEmail(ctx, normalized)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("no user with that email")
		}
		return nil, fmt.Errorf("look up user: %w", err)
	}

	if err := r.GroupStore.AddMember(ctx, groupID, user.ID); err != nil {
		if errors.Is(err, group.ErrAlreadyMember) {
			return nil, fmt.Errorf("user is already a member of this group")
		}
		return nil, fmt.Errorf("add member: %w", err)
	}

	g, err := r.GroupStore.GetByID(ctx, groupID)
	if err != nil {
		return nil, fmt.Errorf("load group: %w", err)
	}
	return groupRecordToModel(g), nil
}

// CreateTransaction is the resolver for the createTransaction field.
func (r *mutationResolver) CreateTransaction(ctx context.Context, input model.CreateTransactionInput) (*model.Transaction, error) {
	_, err := r.requireGroupMember(ctx, input.GroupID)
	if err != nil {
		return nil, err
	}

	if input.Amount <= 0 {
		return nil, fmt.Errorf("amount must be positive")
	}
	if len(input.SplitBetween) == 0 {
		return nil, fmt.Errorf("splitBetween must include at least one user")
	}

	payerID, _ := auth.UserIDFromContext(ctx)
	if input.PaidBy != nil {
		payerID = *input.PaidBy
		isMember, err := r.GroupStore.IsMember(ctx, input.GroupID, payerID)
		if err != nil {
			return nil, fmt.Errorf("check payer membership: %w", err)
		}
		if !isMember {
			return nil, fmt.Errorf("paidBy user is not a member of this group")
		}
	}

	nonMembers, err := r.GroupStore.AreMembers(ctx, input.GroupID, input.SplitBetween)
	if err != nil {
		return nil, fmt.Errorf("check memberships: %w", err)
	}
	if len(nonMembers) > 0 {
		return nil, fmt.Errorf("user %s is not a member of this group", nonMembers[0])
	}

	t, err := r.GroupStore.CreateTransaction(ctx, input.GroupID, input.Description, int64(input.Amount), payerID, input.SplitBetween)
	if err != nil {
		return nil, fmt.Errorf("create transaction: %w", err)
	}
	return txnRecordToModel(t), nil
}

// DeleteTransaction is the resolver for the deleteTransaction field.
func (r *mutationResolver) DeleteTransaction(ctx context.Context, id string) (bool, error) {
	t, err := r.GroupStore.GetTransaction(ctx, id)
	if err != nil {
		if errors.Is(err, group.ErrNotFound) {
			return false, fmt.Errorf("transaction not found")
		}
		return false, fmt.Errorf("load transaction: %w", err)
	}

	if _, err := r.requireGroupMember(ctx, t.GroupID); err != nil {
		return false, fmt.Errorf("transaction not found")
	}

	if err := r.GroupStore.DeleteTransaction(ctx, id); err != nil {
		return false, fmt.Errorf("delete transaction: %w", err)
	}
	return true, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userID, ok := auth.UserIDFromContext(ctx)
	if !ok {
		return nil, nil
	}

	user, err := r.UserStore.GetByID(ctx, userID)
	if err != nil {
		log.Printf("lookup user %s: %v", userID, err)
		return nil, fmt.Errorf("failed to load user")
	}

	return userRecordToModel(user), nil
}

// Groups is the resolver for the groups field.
func (r *queryResolver) Groups(ctx context.Context) ([]*model.Group, error) {
	userID, err := r.requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	records, err := r.GroupStore.ListByUser(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("list groups: %w", err)
	}

	groups := make([]*model.Group, len(records))
	for i, g := range records {
		groups[i] = groupRecordToModel(g)
	}
	return groups, nil
}

// Group is the resolver for the group field.
func (r *queryResolver) Group(ctx context.Context, id string) (*model.Group, error) {
	if _, err := r.requireGroupMember(ctx, id); err != nil {
		return nil, err
	}

	g, err := r.GroupStore.GetByID(ctx, id)
	if err != nil {
		if errors.Is(err, group.ErrNotFound) {
			return nil, nil
		}
		return nil, fmt.Errorf("load group: %w", err)
	}
	return groupRecordToModel(g), nil
}

// Group is the resolver for the group field.
func (r *transactionResolver) Group(ctx context.Context, obj *model.Transaction) (*model.Group, error) {
	g, err := dataloader.For(ctx).GroupLoader.Load(ctx, obj.GroupID)
	if err != nil {
		return nil, fmt.Errorf("load transaction group: %w", err)
	}
	return groupRecordToModel(g), nil
}

// PaidBy is the resolver for the paidBy field.
func (r *transactionResolver) PaidBy(ctx context.Context, obj *model.Transaction) (*model.User, error) {
	u, err := dataloader.For(ctx).UserLoader.Load(ctx, obj.PaidByID)
	if err != nil {
		return nil, fmt.Errorf("load payer: %w", err)
	}
	return userRecordToModel(u), nil
}

// SplitBetween is the resolver for the splitBetween field.
func (r *transactionResolver) SplitBetween(ctx context.Context, obj *model.Transaction) ([]*model.User, error) {
	loaders := dataloader.For(ctx)
	ids, err := loaders.TransactionSplitsLoader.Load(ctx, obj.ID)
	if err != nil {
		return nil, fmt.Errorf("load split users: %w", err)
	}
	if len(ids) == 0 {
		return []*model.User{}, nil
	}
	records, err := loaders.UserLoader.LoadAll(ctx, ids)
	if err != nil {
		return nil, fmt.Errorf("load split user records: %w", err)
	}
	users := make([]*model.User, len(records))
	for i, u := range records {
		users[i] = userRecordToModel(u)
	}
	return users, nil
}

// Group returns GroupResolver implementation.
func (r *Resolver) Group() GroupResolver { return &groupResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Transaction returns TransactionResolver implementation.
func (r *Resolver) Transaction() TransactionResolver { return &transactionResolver{r} }

type groupResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type transactionResolver struct{ *Resolver }
