package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"errors"
	"fmt"

	"github.com/kylejs/splitty/backend/graph/model"
	"github.com/kylejs/splitty/backend/internal/auth"
)

// SignInWithApple is the resolver for the signInWithApple field.
func (r *mutationResolver) SignInWithApple(ctx context.Context, identityToken string) (*model.AuthResponse, error) {
	return nil, fmt.Errorf("not implemented: SignInWithApple")
}

// SendPasscode is the resolver for the sendPasscode field.
func (r *mutationResolver) SendPasscode(ctx context.Context, email string) (*model.SendPasscodeResponse, error) {
	if err := r.PasscodeService.SendPasscode(ctx, email); err != nil {
		if errors.Is(err, auth.ErrUnavailable) {
			return nil, fmt.Errorf("email passcode is not available")
		}
		return nil, err
	}
	return &model.SendPasscodeResponse{Success: true}, nil
}

// VerifyPasscode is the resolver for the verifyPasscode field.
func (r *mutationResolver) VerifyPasscode(ctx context.Context, email string, code string) (*model.AuthResponse, error) {
	result, err := r.PasscodeService.VerifyPasscode(ctx, email, code)
	if err != nil {
		if errors.Is(err, auth.ErrUnavailable) {
			return nil, fmt.Errorf("email passcode is not available")
		}
		return nil, err
	}
	return &model.AuthResponse{
		AccessToken:  result.AccessToken,
		RefreshToken: result.RefreshToken,
		User: &model.User{
			ID:          result.User.ID,
			Email:       result.User.Email,
			DisplayName: result.User.DisplayName,
		},
	}, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, refreshToken string) (*model.AuthResponse, error) {
	return nil, fmt.Errorf("not implemented: RefreshToken")
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	return nil, fmt.Errorf("not implemented: Me")
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
