name: Backend

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      has-changes: ${{ steps.check.outputs.has-changes }}
    steps:
      - uses: actions/checkout@v4
      - id: check
        uses: ky1ejs/check-diff-paths-action@v0.3.0
        with:
          paths: "^backend\\/.*"
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: check-changes
    if: needs.check-changes.outputs.has-changes == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod
      - name: Generate GraphQL code
        run: go run github.com/99designs/gqlgen generate
      - run: go build ./...
      - run: go test ./...
